sudo: false
language: node_js
node_js:
    - 8
    - 9
    - 10
    - 11
cache:
    directories:
        - node_modules
        - "$HOME/.npm"
script:
    - npm run lint
    - npm run test-cov
after_script:
    - npm install codecov
    - ./node_modules/.bin/codecov
deploy:
    - provider: npm
      email: "lvchengbin59@gmail.com"
      api_key: "25360aee-43c8-4c4f-baa7-b4cd5886c89a"
      on:
          branch: master
          node: 11

